#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require

layout(local_size_x = 1) in;

layout(buffer_reference, scalar) readonly buffer VisibleInstanceBuffer { uint count; uint data[]; };
layout(buffer_reference, scalar) writeonly buffer IndirectDispatch { uint x; uint y; uint z; };

layout(push_constant) uniform Push {
    InstanceBuffer instances;
    VisibleInstanceBuffer visible_instances;
    IndirectDispatch expand_args;
    IndirectDispatch cull_args;
} pc;

void main() {
    pc.expand_args.x = (pc.visible_instances.count + 63u) / 64u;
    pc.expand_args.y = 1u;
    pc.expand_args.z = 1u;

    pc.cull_args.x = 0u;
    pc.cull_args.y = 1u;
    pc.cull_args.z = 1u;
}