function(lumen_generate_asset_rc OUTPUT_RC)
    cmake_parse_arguments(ARG "" "" "FILES" ${ARGN})
    set(ASSET_DIRS ${ARG_UNPARSED_ARGUMENTS})
    set(RC_CONTENT "")

    foreach(DIR ${ASSET_DIRS})
        if(NOT EXISTS ${DIR})
            continue()
        endif()

        file(GLOB_RECURSE ASSET_FILES CONFIGURE_DEPENDS "${DIR}/*")
        get_filename_component(DIR_NAME ${DIR} NAME)

        foreach(FILE ${ASSET_FILES})
            file(RELATIVE_PATH REL_PATH ${DIR} ${FILE})
            string(REGEX REPLACE "[^A-Za-z0-9]" "_" SAFE_NAME ${REL_PATH})
            string(TOUPPER "${DIR_NAME}_${SAFE_NAME}" RES_NAME)
            string(APPEND RC_CONTENT "${RES_NAME} RCDATA \"${FILE}\"\n")
        endforeach()
    endforeach()

    foreach(FILE ${ARG_FILES})
        if(NOT EXISTS ${FILE})
            continue()
        endif()
        get_filename_component(FILE_NAME ${FILE} NAME)
        string(REGEX REPLACE "[^A-Za-z0-9]" "_" SAFE_NAME ${FILE_NAME})
        string(TOUPPER "${SAFE_NAME}" RES_NAME)
        string(APPEND RC_CONTENT "${RES_NAME} RCDATA \"${FILE}\"\n")
    endforeach()

    file(WRITE ${OUTPUT_RC} "${RC_CONTENT}")
endfunction()